name: build

on:
  workflow_call:
    inputs:
      image_name:
        description: Name of the image to build
        required: true
        type: string
      image_tag:
        description: Tag of the image to build
        default: latest
        required: true
        type: string
      version_bump:
        description: Version bump type (major, minor, patch, none)
        required: false
        default: none
        type: string

  workflow_dispatch:
    inputs:
      image_name:
        description: Name of the image to build
        required: true
      image_tag:
        description: Tag of the image to build
        default: latest
        required: true
      version_bump:
        description: Version bump type (major, minor, patch, none)
        required: false
        default: none

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Resolve image tag
        id: tag
        shell: bash
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.image_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          if [[ "${{ inputs.version_bump }}" == "none" ]]; then
            echo "Using provided image_tag: ${{ inputs.image_tag }}"
            echo "tag=${{ inputs.image_tag }}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "version_bump=${{ inputs.version_bump }} â†’ ignoring image_tag"

          tags=$(curl -s -H "Authorization: Bearer $GH_TOKEN" "https://ghcr.io/v2/${IMAGE#ghcr.io/}/tags/list")
          latest=$(echo "$tags" | jq -r '.tags[]' | sort -V | tail -n 1)

          latest=${latest:-v0.0.0}
          echo "Latest version: $latest"

          version=${latest#v}
          IFS='.' read -r major minor patch <<< "$version"

          case "${{ inputs.version_bump }}" in
            major)
              major=$((major+1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor+1))
              patch=0
              ;;
            patch)
              patch=$((patch+1))
              ;;
            *)
              echo "Invalid version_bump"
              exit 1
              ;;
          esac

          next="v$major.$minor.$patch"
          echo "Resolved tag: $next"
          echo "tag=$next" >> "$GITHUB_OUTPUT"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.image_name }}
          tags: |
            type=raw,value=${{ (startsWith(inputs.image_tag, 'v') || inputs.image_tag == 'latest') && inputs.image_tag || format('v{0}', inputs.image_tag) }}
            type=raw,value=latest,enable=${{ inputs.image_tag != 'latest' }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.image_name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
