name: build

on:
  workflow_call:
    inputs:
      image_name:
        description: Name of the image to build
        required: true
        type: string
      image_tag:
        description: Tag of the image to build
        default: latest
        required: true
        type: string
      version_bump:
        description: Version bump type (major, minor, patch, none)
        required: false
        default: none
        type: string

  workflow_dispatch:
    inputs:
      image_name:
        description: Name of the image to build
        required: true
      image_tag:
        description: Tag of the image to build
        default: latest
        required: true
      version_bump:
        description: Version bump type (major, minor, patch, none)
        required: false
        default: none

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Resolve image tag
        id: tag
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_NAME: ${{ inputs.image_name }}
        run: |
          set -e

          if [[ "${{ inputs.version_bump }}" == "none" ]]; then
            echo "tag=${{ inputs.image_tag }}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Fetching versions for package: $PACKAGE_NAME owned by $OWNER"
          echo ""https://api.github.com/users/hilmoo/packages/container/containers%2F$PACKAGE_NAME/versions""

          PACKAGE_VERSION=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/users/hilmoo/packages/container/containers%2F$PACKAGE_NAME/versions" \
            | jq -r '
                if type=="array" then
                  (
                    [.[0].metadata.container.tags[]? | select(. != "latest")]
                    + [.[].metadata.container.tags[]? | select(. != "latest")]
                  ) | .[0]
                else
                  empty
                end
              ')

          if [ -z "$PACKAGE_VERSION" ] || [ "$PACKAGE_VERSION" = "null" ]; then
            echo "No existing tags found. Defaulting to v0.0.0"
            latest="v0.0.0"
          else
            latest=$(echo "$PACKAGE_VERSION" | sort -V | tail -n 1)
            echo "Latest version found: $latest"
          fi

          IFS='.' read -r major minor patch <<< "$PACKAGE_VERSION"

          major=${major:-0}; minor=${minor:-0}; patch=${patch:-0}

          case "${{ inputs.version_bump }}" in
            major) major=$((major+1)); minor=0; patch=0 ;;
            minor) minor=$((minor+1)); patch=0 ;;
            patch) patch=$((patch+1)) ;;
            *) echo "Error: Invalid version_bump input: ${{ inputs.version_bump }}"; exit 1 ;;
          esac

          next="v$major.$minor.$patch"

          echo "Resolved tag: $next"
          echo "tag=$next" >> "$GITHUB_OUTPUT"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.image_name }}
          tags: |
            type=raw,value=${{ steps.tag.outputs.tag }}
            type=raw,value=latest,enable=${{ steps.tag.outputs.tag != 'latest' }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.image_name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
